Update users function
foundersandcoders/Live-Peers pull request #88
Opened 2017-03-01 16:08 UTC by esraajb

2017-03-01 16:14 UTC, njsfield commented on public/helpers/update-users.js
> +        addUser('moderator', user);
I think this would need to be `addUser('mentor', user)` if the mentor doesn't exist

2017-03-01 16:14 UTC, njsfield commented on public/helpers/update-users.js
> +        addUser('mentor', user);
I think this would need to be addUser('moderator', user) if the mentor doesn't exist

2017-03-01 16:16 UTC, esraajb commented on public/helpers/update-users.js
> +        addUser('mentor', user);
notice that i've already removed the exclamation mark from the first if

2017-03-01 16:18 UTC, njsfield commented on public/helpers/update-users.js
> +        addUser('mentor', user);
Ah cool, sweet :)

2017-03-01 16:26 UTC, njsfield commented on public/helpers/update-users.js
> +  newUser.innerHTML = user.username;
Can we do .textContent instead?

2017-03-01 16:27 UTC, njsfield commented on public/helpers/update-users.js
> +  const className = ".class__-list";
Needs to be `const className = ".online__-list";`

So that it will return the correct class; e.g. 'online__students-list'

2017-03-01 16:29 UTC, njsfield commented on public/js/chat.js
> +    comms.registerHandler(this.app, 'REGISTER', displayTextMessage(data)); //data: object with username and message
For register it needs to be `updateUsers(sender, users)`

2017-03-01 16:29 UTC, njsfield commented on public/js/chat.js
> +    comms.registerHandler(this.app, 'MESSAGE', updateUsers(sender, users));
For message it needs to be displayTextMessage(data)

2017-03-01 16:40 UTC, njsfield commented on public/helpers/update-users.js
> +  list.appendChild(newUser);
Before this, we need to do this;
```javascript
list.innerHTML = ''
```
To clear all the users in the list items

Essentially, when this function `updateUsers` gets called, it'll rebuild the users every time

2017-03-01 16:41 UTC, jsms90 requested changes
Cool logic for `ceateClassName`. Nice work :+1:

2017-03-01 16:41 UTC, jsms90 commented on public/helpers/update-users.js
> +const updateUsers = (sender, users) => {
Can we change `users` to `participants` everywhere in this file, so that it is more in line with how we are referring to people in Noga's designs?

2017-03-01 16:41 UTC, jsms90 commented on public/helpers/update-users.js
> +    if(user.permissions.length == 2){
Let's change this to be more specific:
```javascript
if(participant.permissions.includes('AV') && participant.permissions.includes('CHAT'))
```

2017-03-01 16:41 UTC, jsms90 commented on public/helpers/update-users.js
> +      else{
Similarly, let's future proof ourselves:
```javascript
else if(participant.permissions.length === 1 && participant.permissions.includes('CHAT'))
```

2017-03-01 17:09 UTC, njsfield approved these changes

2017-03-02 11:03 UTC, jsms90 approved these changes
Going to have to fix `updateParticipants` based on changes to the default permissions logic

2017-03-02 11:03 UTC, jsms90 commented on public/helpers/update-users.js
> +    if(participant.permissions.includes('AV') && participant.permissions.includes('CHAT')){
This logic actually doesn't quite work - my bad!
(During this sprint) a mentor doesn't begin with CHAT and AV permissions by default any more, so when they first join the room, they would drop into the `else if` block and appear as a student.

2017-03-02 11:03 UTC, merged